languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "Portfolio"
logo = "img/wyse.png"
description = "Hello and welcome to the personal blog of a recently graduated software engineer."
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"

[author]
  name = "Wai Yan"
  image = "img/mdy.jpg"
  headline = "Welcome to my portfolio. I'm Wai Yan. A software engineer, major in Cyber Security, who recently graduated. Check out my blogs."
  bio = "Hope you enjoy the article or learn something new."
  links = [
    { linkedin = "https://www.linkedin.com/in/wai-yan-951b50221/" },
    { instagram = "https://www.instagram.com/wai30yan/" },
    { github = "https://github.com/Wai30Yan" },
  ]
